version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app:cached
    working_dir: /app
    stdin_open: true
    env_file:
      - ./.env
    command: sh -c 'npm install && npm run dev'
    ports:
      - 3001:3000
