name: Deploy to S3 for storybook
on:
  issue_comment:
    types: [created]
  push:
    branches:
      - main
    paths:
      - "app/context.server.ts"
      
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  check-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      deploy: ${{ steps.check-deploy.outputs.deploy }}
      ref: ${{ steps.check-deploy.outputs.ref }}
      dest_dir: ${{ steps.check-deploy.outputs.dest_dir }}
      is_pr: ${{ steps.check-deploy.outputs.is_pr }}
    steps:
      - name: Check if deploy is needed and set env
        id: check-deploy
        run: |
          if [ -n "${{ github.event.issue.pull_request }}" ] && [ "${{ github.event.comment.body }}" == "/deploy-storybook" ]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "is_pr=true" >> $GITHUB_OUTPUT
            echo "ref=refs/pull/${{ github.event.issue.number }}/head" >> $GITHUB_OUTPUT
            echo "dest_dir=pr_${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "push" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "ref=${{ github.ref }}" >> $GITHUB_OUTPUT
            echo "dest_dir=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi
  pr_commented:
    name: PR comment
    needs: check-deploy
    if: ${{needs.check-deploy.outputs.deploy == 'true'}} && ${{needs.check-deploy.outputs.is_pr == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.check-deploy.outputs.ref }}
      - name: post preview url to pull-request
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'storybookのURLはこちら\n' +
                "https://test/${{needs.check-deploy.outputs.dest_dir}}/index.html"
            })
