name: Deploy to S3 for storybook
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "app/context.server.ts"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      deploy: ${{ steps.check-deploy.outputs.deploy }}
      ref: ${{ steps.check-deploy.outputs.ref }}
    steps:
      - name: Check if deploy is needed and set ref
        id: check-deploy
        run: |
            if [ -n "${{ github.event.issue.pull_request }}" ]; then
              if [ "${{ github.event.comment.body }}" == "/deploy-storybook" ]; then
                echo "deploy=true" >> $GITHUB_OUTPUT
                echo "ref=refs/pull/${{ github.event.issue.number }}/head" >> $GITHUB_OUTPUT
              else
                echo "deploy=false" >> $GITHUB_OUTPUT
              fi
            elif [ "${{ github.event.pull_request.merged }}" == "true" ]; then
              echo "deploy=true" >> $GITHUB_OUTPUT
              echo "ref=refs/heads/main" >> $GITHUB_OUTPUT
            elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              echo "deploy=true" >> $GITHUB_OUTPUT
              echo "ref=${{ github.ref }}" >> $GITHUB_OUTPUT
            else
              echo "deploy=false" >> $GITHUB_OUTPUT
            fi
  pr_commented:
    name: PR comment
    needs: check-deploy
    if: ${{needs.check-deploy.outputs.deploy == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.check-deploy.outputs.ref }}
      - name: set upload destination directory name
        run: |
          DEST_DIR=${{ github.event.issue.number }}
          [ -z $DEST_DIR ] && DEST_DIR=main
          echo "DEST_DIR=${DEST_DIR}" >> $GITHUB_ENV
      - run: |
          echo A comment on PR "${DEST_DIR}"
