name: Deploy to S3 for storybook
on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set upload destination directory name
        run: |
          DEST_DIR=${{ github.event.issue.number }}
          [ -z $DEST_DIR ] && DEST_DIR=main
          echo "DEST_DIR=${DEST_DIR}" >> $GITHUB_ENV
      - run: |
          echo A comment on PR "${DEST_DIR}"
